### ISSUE TITLE
Is interpolation needed?

### ISSUE THREAD

**Issue by cameralabhw** [ucsd-hdsi-dvs/V2CE-Toolbox#2]
Hello and thank you for your great work!

With previous event simulators, it was often recommended to interpolate RGB frames from the original input sequence to get more realistic event timestamps.

If for example I have 120 fps input video, is separate frame interpolation needed with your method, or will the simulator produce accurate events straight away?

Also, in the paper you mention that you use 30 fps in your input sequences, will the simulator work with higher fps and does it automatically take that into account when creating the timestamps for the events?

**Comment by miracleyoo** [comment]
This is not needed. Our simulator doesn't require you to interpolate before feeding your video in. Also, although our method is model-based and the model is mostly trained on 30FPS videos, there is no limitation on your input FPS, as the mechanism is trying to interpolate the spatial-temporal space between any two input frames based on the frame sequence. 

Although it's not strictly tested and reported on other FPS videos, we tried 15FPS and 60FPS input videos before and it's working as expected. Also, you can treat a 2N FPS video as an N FPS video with a higher moving speed, and since the input video includes paired events and videos are collected at all different speeds, in theory, the original input FPS should also not be an issue. 

But please be aware, a relatively higher input video FPS will lead to a finer-grained event stream output, as the predicted voxel grid has a better time resolution. However, I don't recommend you do extra frame interpolation if your original video already has an FPS of more than 25Hz. So to summarize, in your case, I'll say it's better to keep your input video as it is :) Again, thanks for your interest in our project!
