### ISSUE TITLE
Problem in generating events with sequences of frames

### ISSUE THREAD

**Issue by ChiaraBoretti** [ucsd-hdsi-dvs/V2CE-Toolbox#3]
Hi, 
Thanks for this beautiful work! 
I'm trying to generate the events stream from a sequence of images with a resolution of 346x260 but I get this error:  

Traceback (most recent call last):
  File "/srv/newpenny/Robotics/chiara/V2CE-Toolbox/v2ce.py", line 344, in <module>
    event_stream_per_frame.extend(ldati(stage2_input[i:i+args.stage2_batch_size]))
  File "/srv/newpenny/Robotics/chiara/V2CE-Toolbox/scripts/LDATI.py", line 197, in sample_voxel_statistical
    logger.debug(f"max of additional_ts: {torch.max(additional_ts)}")
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument

The greyscale video of events is correctly generated but the .npz file is not. Do you have any idea of what could be the problem?

**Comment by Asa-Hopkins** [comment]
I encountered this issue too, it seems to be because "additional_ts" is sometimes empty and the maximum value of an empty tensor isn't defined. Since the line in question is a debugging line I just commented it out, as well as the next line where it tries to check the minimum because of the same error. It seems to work after that.

**Comment by miracleyoo** [comment]
Thank you @Asa-Hopkins for the trial and explanation. Yes, the error message shows that the variable `additional_ts` in your case is completely empty, which could be caused by an empyt input `y`. I'm pushed a update to disable max/min check when `additional_ts` is empty. If possible, would any of you mind sending a video sample that could trigger this bug? I want to look into it since I haven't encountered the same issue previously. Thanks for your support.

**Comment by miracleyoo** [comment]
For the easiest solution of this types of errors at the moment, you can simply set the `--log_level` to `info`.
