### ISSUE TITLE
one  question

### ISSUE THREAD

**Issue by Suquirrel** [ucsd-hdsi-dvs/V2CE-Toolbox#4]
Hi, I am having the following problem when applying your command template:
My command is as follows:
python v2ce.py --out_name_suffix=release --max_frame_num=321 --infer_type=center -i 'D:\study\python\V2CE-Toolbox-master-test.mp4' -b 4 -- write_event_frame_video -l info
The error message is as follows:
index -1 is out of bounds for axis 0 with size 0
Why is this, the video I'm using is the V2E tennis test video, which I've cropped to 346*260 mp4 format

Translated with DeepL.com (free version)
![photo](https://github.com/user-attachments/assets/cd771a48-69dc-4d3b-ac56-cf936f914752)

**Comment by Suquirrel** [comment]
https://github.com/user-attachments/assets/d62d617c-97ed-40aa-b890-3584558c1aed

this  is   my  viedeo

**Comment by miracleyoo** [comment]
Hi @Suquirrel , thanks for you interest in our project. I've investigated in your issue, downloaded and tried to infer your uploaded video using v2ce. However, it runs normally without problem here from my end. 
<img width="1395" alt="image" src="https://github.com/user-attachments/assets/b63b368b-2360-47fb-a30d-78741f2df80f">

From your error message, it indicates that the loaded video has 0 frames. In other words, the program may not detect your video at the input path. Please make sure your input video path is correct, and since you are running it in Windows, using "<path>" instead of '<path>' sometimes could be a safer option. 

If your problem still cannot be solved, please let me know.

**Comment by miracleyoo** [comment]
Processed video for your reference:
https://github.com/user-attachments/assets/bcec01eb-9478-4907-85ed-99688cecb150

**Comment by miracleyoo** [comment]
Processed video for your reference:

https://github.com/user-attachments/assets/ea16f586-bf2a-4d4f-98bf-897da009d0ab

**Comment by Suquirrel** [comment]
thank you ,I had solved this question.
under Windows,  the path need to be removed the ' '
